- src/components/PasswordInput/PasswordInput.js
- src/components/PasswordInput/index.js
- src/i18n.js
- src/pages/Admin/SignUp/SignUp.js
- Shows/hides the password field. 
- Creates a new component PasswordInput
> feat: show hide password in signup

- src/components/App/App.js
- src/components/CookieBanner/CookieBanner.js
- src/components/CookieBanner/CookieBanner.test.js
- src/components/CookieBanner/index.js
- src/components/ErrorBoundary/ErrorBoundary.js
- src/components/Router/Router.js
- src/constants/RoutesConstants.js
- src/i18n.js
- src/pages/Admin/common/index.js
- src/pages/OnBoardingContent/OnBoardingContent.js
- src/services/authentication.js
- yarn.lock
- This adds cookie banner 
- Banner is sticked to top until user clicks on 'X'
- Once user closes the banner it'll set a variable on localStorage like we do for show/skip tutorial
> feat: Add cookie banner

- src/i18n.js
- src/pages/OnBoardingContent/OnBoardingContent.js
- Adds some improvements in landing page for desktop
> feat: improvements in landing page for desktop

- src/pages/OnBoardingContent/OnBoardingDesktop.js
- Hide back arrow in first page
> Fix bug onboarding consumidor

- src/components/Footer/Footer.js
- Fixes https://trello.com/c/i20yFmeE/78-ocultar-link-nos-itens-privacidade-e-contactos-no-footer
> fix: remove privacy and contacts links

- src/pages/Admin/common/index.js
- fixes https://trello.com/c/sjAqDrH3/84-senha-por-nome-mobile
> fix: name not seen on queue

- src/i18n.js
- src/pages/OnBoardingContent/OnBoardingDesktop.js
- src/pages/OnBoardingContent/StepperContent.js
https://trello.com/c/ZyMBTXj7/86-ajustar-como-funciona-p-remo%C3%A7%C3%A3o-de-email-e-adi%C3%A7%C3%A3o-de-nr-tlm-consumidor
> feat: Adjust how it works in consumer desktop version

- src/components/HomeLayout/HomeLayout.js
- src/pages/OnBoardingContent/OnBoardingMobile.js
- src/pages/TicketContent/Ticket.js
- Fixes first page of /tirar-senha
- Fixes step 4 of consumer onboarding
> fix: onboarding and ticket first screen

- src/components/Footer/Footer.js
- src/components/Router/Router.js
- src/i18n.js
- src/pages/HomeContent/Legal.js
- src/pages/HomeContent/index.js
- Adds privacy policy;
- Changes terms and conditions to be used for both pages (terms and privacy)
> feat: add privacy policy

- src/components/Footer/Footer.js
- src/constants/RoutesConstants.js
- src/i18n.js
- src/pages/HomeContent/AboutUs.js
> Added About us page access point + copy adjustments

- docs/serverless.md
- src/services/authentication.js
> Added email to users collection

- src/components/AdminLayout/AdminLayout.js
- src/components/OnBoardingLayout/Admin/DesktopLayout.js
- src/i18n.js
- src/pages/Admin/Home/Home.js
- src/pages/Admin/Login/Login.js
- src/pages/Admin/SignUp/SignUp.js
- src/pages/Admin/WelcomePanel/WelcomePanel.js
> Open authentication public

- src/components/AdminLayout/AdminLayout.js
- src/components/HomeLayout/HomeLayout.js
- src/components/OnBoardingLayout/Admin/MobileLayout.js
- src/components/OnBoardingLayout/OnBoardingLayoutDesktop.js
- src/components/OnBoardingLayout/OnBoardingLayoutMobile.js
- src/pages/Admin/AddConsumer/AddConsumer.js
- src/pages/Admin/Home/Home.js
- src/pages/HomeContent/AboutUs.js
- src/pages/HomeContent/Home.js
> add root url to logos - needs refactor in the future

- src/components/OnBoardingLayout/Admin/DesktopLayout.js
- src/pages/Admin/OnBoarding/OnBoarding.js
fixed to work both on desktop and mobile leading to registration page.
fixes #160
> Onboarding flow on mobile is leading to typeform

- src/components/App/App.js
> Removed cookie banner from status screen

- src/i18n.js
Changed cliente to Cliente in i18n - BugFix
> Changed cliente to Cliente in i18n - BugFix

- src/pages/QueueStatus/QueueStatus.js
> Added yellow highlight on update

- src/components/BurgerMenu/StoreMenuOptions.js
> fix: cartaz opens in new tab

- src/serviceWorker.js
> feat: cache busting

- src/components/BurgerMenu/StoreMenuOptions.js
- src/i18n.js
> add /create-queue to menu

- functions/index.js
- src/pages/Admin/Queue/Manage/Manage.js
Change create queue method to support fixed queue id's
> Fixed Queue ID

- functions/index.js
> sms in english support
